// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/tools/get_issue_detail.ts";
import * as module_3 from "../../agent/tools/get_latest_issue.ts";
import * as module_4 from "../../agent/tools/get_learning_path.ts";
import * as module_5 from "../../agent/tools/get_post.ts";
import * as module_6 from "../../agent/tools/list_posts.ts";
import * as module_7 from "../../agent/tools/search_glossary.ts";
import * as module_8 from "../../agent/tools/search_issues.ts";
import * as module_9 from "../../agent/tools/web_search.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/get_issue_detail.ts": module_2,
                  "tools/get_latest_issue.ts": module_3,
                  "tools/get_learning_path.ts": module_4,
                  "tools/get_post.ts": module_5,
                  "tools/list_posts.ts": module_6,
                  "tools/search_glossary.ts": module_7,
                  "tools/search_issues.ts": module_8,
                  "tools/web_search.ts": module_9
                })
            })
    })
});

export default moduleMap;
