packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
